### ISSUE TITLE
Doesn't work with Safari, or am I missing something?

### ISSUE THREAD

**Issue by nenadapp** [mciastek/sal#15] opened 2019-01-23 07:54 UTC
No idea.

**Comment by mciastek** [comment] 2019-01-23 16:26
You need to use polyfill to make sal.js work in Safari. See introduction note in [README.md](https://github.com/mciastek/sal/blob/master/README.md):

> **Note:** Intersection Observer API is an experimental technology so be sure to consult the [browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Browser_compatibility) and consider using a [polyfill](https://github.com/w3c/IntersectionObserver/tree/master/polyfill).

I'm closing this issue. Please reopen if needed.

**Closed by mciastek** 2019-01-23 16:26 UTC

**Comment by Mapiac** [comment] 2019-09-27 00:49
Looks like no pollyfill required now as Safari supports Intersection Observer. Curious if you can use requestAnimationFrame with this library as we might wrap in FastDOM

**Comment by mciastek** [comment] 2019-09-30 08:39
I tested sal.js on Safari 12.1 and I can confirm it works. As you can see in [Can I use](https://caniuse.com/#feat=intersectionobserver). 

> Curious if you can use requestAnimationFrame with this library as we might wrap in FastDOM

@Mapiac can you elaborate more on that?
