### ISSUE TITLE
GatsbyJS: tagged items wont appear after first load

### ISSUE THREAD

**Issue by juancarloselorriaga** [mciastek/sal#35] opened 2020-02-05 00:52 UTC
"gatsby": "^2.19.7",
"gatsby-plugin-scroll-reveal": "0.0.6",

On first load page the items are revealing with animations and with no problems. But if I change to another page (client protected routes) and go back to my animated page, the items wont appear again,

**Comment by mciastek** [comment] 2020-02-07 18:21
Hi, thanks for submitting this issue. I'd suggest to open an issue in the [gatsby-plugin-scroll-reveal](https://github.com/solublestudio/gatsby-plugin-scroll-reveal) repository, because it can be related more to this library. If you'll find that it's a problem with sal.js, please create a repository to reproduce the bug.

For now I'm closing this issue. Please reopen, when needed.

**Closed by mciastek** 2020-02-07 18:21 UTC
