### ISSUE TITLE
sal.js stopped working in Safari and Chrome for SVG's paths

### ISSUE THREAD

**Issue by jirsbek** [mciastek/sal#48] opened 2020-04-09 09:54 UTC
First of all, thank you for great library, I really like to use it.

I believe, after macOS update (10.15.4), especially Safari update 13.1 and Chrome (80+) sal.js stopped working for SVG's paths animations.

I've simplified the problem in Codepen. Fade-in works well in Firefox, but not in current Safari or Chrome (page is blank). I believe it has something to do with CSS `opacity` property and `[data-sal|=fade]` selector. But I might be wrong.

https://codepen.io/jirsbek/pen/zYvYKXL

**Comment by mciastek** [comment] 2020-04-15 10:22
I did a quick test if Intersection Observer can detect elements inside SVG context and it appears that it doesn't find anything. Strangely, it works in latest Firefox, but fails in Chrome and Safari, as you mentioned.

There are a couple of issues in w3c repository regarding this problem - https://github.com/w3c/IntersectionObserver/issues/223 and https://github.com/w3c/IntersectionObserver/issues/376. It seems that none of them has been resolved yet. My guess is, this bug is probably caused by SVG's separate document tree. I mean, SVG has different context (something like iframes) and some browsers didn't implement elements detection for this nested context.

I would recommend embedding every `<path/>` into its own `<svg/>` and then animate them. That's how it works on sal's [github page](https://mciastek.github.io/sal/). 

It think this bug is related to implementation of Intersection Observer in browsers and it's not caused directly by sal.js. I'm closing this issue. Reopen if needed.

**Closed by mciastek** 2020-04-15 10:22 UTC
